export const POST_LOGIN_JWT = "POST_LOGIN_JWT";
export const PUT_FORGOT_PASSWORD = "PUT_FORGOT_PASSWORD";
export const POST_RESISTRATION = "POST_RESISTRATION";

export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCTS = "DELETE_PRODUCTS";
export const SORT_PRODUCTS = "SORT_PRODUCTS";
export const PRODUCT_IMAGE = "PRODUCT_IMAGE";
export const SEARCH_PRODUCT = "SEARCH_PRODUCT";

export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const DELETE_CATEGORIES = "DELETE_CATEGORIES";
export const SORT_CATEGORIES = "SORT_CATEGORIES";
export const SEARCH_CATEGORY = "SEARCH_CATEGORY";

export const SUB_CATE_BY_CATE = "SUB_CATE_BY_CATE";

export const GET_SUB_CATEGORIES = "GET_SUB_CATEGORIES";
export const GET_ALL_SUB_CATEGORIES = "GET_All_SUB_CATEGORIES";
export const CREATE_SUB_CATEGORY = "CREATE_SUB_CATEGORY";
export const UPDATE_SUB_CATEGORY = "UPDATE_SUB_CATEGORY";
export const DELETE_SUB_CATEGORIES = "DELETE_SUB_CATEGORIES";
export const SORT_SUB_CATEGORIES = "SORT_SUB_CATEGORIES";
export const SEARCH_SUB_CATEGORY = "SEARCH_SUB_CATEGORY";
